<a href="https://colab.research.google.com/github/dekoska/machine-learning-bootcamp/blob/main/supervised/02_regression/01_linear_regression_normal_equation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
!pip install scikit-learn

In [4]:
import numpy as np

In [5]:
X1 = np.array([1,2,3,4,5,6])
Y = np.array([3000,3250,3500,2750,4000,4250])
m = len(X1)

In [6]:
X1 = X1.reshape(m,1)
print(X1)
print(X1.shape)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
(6, 1)


In [7]:
bias = np.ones((m,1)) #bias-wektor wyrazów wolnych
print(bias)
print(bias.shape)

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]
(6, 1)


In [8]:
X = np.append(bias, X1, axis=1)
print(X)
print(X.shape)

[[1. 1.]
 [1. 2.]
 [1. 3.]
 [1. 4.]
 [1. 5.]
 [1. 6.]]
(6, 2)


### Równanie normalne

Regresja liniowa w $R^2$:
$$Y = w_0 + w_1X_1$$  
$$Y = W^TX$$  

gdzie:  
$$W= \begin{bmatrix}w_0 \\ w_1\end{bmatrix}, \quad X= \begin{bmatrix}1 \\ X_1\end{bmatrix}, \quad W^T= \begin{bmatrix}w_0 & w_1\end{bmatrix}$$  

Stąd:  
$$Y = W^TX = \begin{bmatrix}w_0 & w_1\end{bmatrix} \cdot \begin{bmatrix}1 \\ X_1\end{bmatrix} = w_0 + w_1X_1$$  

Równanie normalne - równanie pozwalające obliczyć minimum funkcji straty (o ile istnieje):  
$$W = (X^TX)^{-1}(X^TY)$$


###numpy

In [9]:
np.dot(X.T, X) #Xtransponowane * X

array([[ 6., 21.],
       [21., 91.]])

In [10]:
L = np.linalg.inv(np.dot(X.T, X)) #odwrocenie Xtransponowanego * X
L

array([[ 0.86666667, -0.2       ],
       [-0.2       ,  0.05714286]])

In [11]:
P = np.dot(X.T, Y)
P

array([20750., 76500.])

In [13]:
W = np.dot(L, P)
W
# Y = 2683 * 221X1 | w0=2683, w1=221

array([2683.33333333,  221.42857143])

### scikit-learn


In [14]:
from sklearn.linear_model import LinearRegression

regression = LinearRegression()
regression.fit(X1, Y) #fit dopasowuje dane

print(regression.intercept_) #wspolczynnik w0
print(regression.coef_[0]) #wspolczynnik dla pierwszej zmiennej niezależnej czyli w1

2683.3333333333335
221.42857142857142
