<a href="https://colab.research.google.com/github/dekoska/machine-learning-bootcamp/blob/main/supervised/02_regression/02_gradient_descent.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install scikit-learn

In [2]:
import numpy as np
import pandas as pd
import plotly.express as px

np.random.seed(42)

In [5]:
X1 = np.array([1, 2, 3, 4, 5, 6])
Y = np.array([3000, 3250, 3500, 3750, 4000, 4250])
m = len(X1)

print(f'Lata pracy: {X1}')
print(f'Wynagrodzenie: {Y}')
print(f'Liczba próbek: {m}')

Lata pracy: [1 2 3 4 5 6]
Wynagrodzenie: [3000 3250 3500 3750 4000 4250]
Liczba próbek: 6


In [7]:
X1 = X1.reshape(m, 1)
Y = Y.reshape(-1, 1)
print(X1)
print(X1.shape)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
(6, 1)


In [8]:
bias = np.ones((m, 1))
print(bias)
print(bias.shape)

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]
(6, 1)


In [9]:
X = np.append(bias, X1, axis=1)
print(X)
print(X.shape)

[[1. 1.]
 [1. 2.]
 [1. 3.]
 [1. 4.]
 [1. 5.]
 [1. 6.]]
(6, 2)


In [10]:
eta = 0.01 #wskaznik uczenia
weights = np.random.randn(2, 1)
print(X)
print(weights)

[[1. 1.]
 [1. 2.]
 [1. 3.]
 [1. 4.]
 [1. 5.]
 [1. 6.]]
[[ 0.49671415]
 [-0.1382643 ]]


In [22]:
intercept = [] #w0
coef = [] #w1

for i in range(4500):
  gradient = (2 / m) *  X.T.dot(X.dot(weights) - Y)
  weights = weights - eta * gradient
  intercept.append(weights[0][0])
  coef.append(weights[1][0])

print(weights)

[[2750.]
 [ 250.]]


In [23]:
df = pd.DataFrame(data={'intercept' : intercept, 'coef' : coef})
df.head()

intercept   coef
0     2750.0  250.0
1     2750.0  250.0
2     2750.0  250.0
3     2750.0  250.0
4     2750.0  250.0

In [24]:
px.line(df, y = 'intercept', width = 800, title = 'dopasowanie: intercept')

In [18]:
px.line(df, y = 'coef', width = 800, title = 'dopasowanie: coef')